// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16
// (BUNNY16_), for each depth of the screen buffer:
// - 16 and 8 bpp: runs per row, _ROWS[y].._ROWS[y + 1] index those of row y
// - 1 bpp: _MASK1[y] the pixels drawn, _WHITE1[y] the white ones, the top bit
//   the leftmost pixel
#pragma once
#include <stdint.h>

typedef struct BunnyRun { uint8_t x, len, white; } BunnyRun;

#define BUNNY16_W 16
#define BUNNY16_H 16
static const uint16_t BUNNY16_ROWS[17] = { 0, 2, 3, 4, 7, 14, 19, 24, 27, 32, 37, 42, 45, 50, 51, 53, 55 };
static const BunnyRun BUNNY16_RUNS[55] = {
    { 4, 3, 0 },
    { 9, 3, 0 },
    { 4, 8, 0 },
    { 4, 8, 0 },
    { 4, 1, 0 },
    { 5, 6, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 1, 1 },
    { 6, 1, 0 },
    { 7, 2, 1 },
    { 9, 1, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 2, 0 },
    { 9, 2, 1 },
    { 11, 1, 0 },
    { 2, 2, 0 },
    { 4, 3, 1 },
    { 7, 2, 0 },
    { 9, 3, 1 },
    { 12, 2, 0 },
    { 2, 3, 0 },
    { 5, 7, 1 },
    { 12, 2, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 1, 1 },
    { 6, 4, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 6, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 8, 0 },
    { 4, 2, 0 },
    { 10, 2, 0 },
    { 4, 2, 0 },
    { 10, 2, 0 }
};
static const uint16_t BUNNY16_MASK1[16] = { 0x0E70, 0x0FF0, 0x0FF0, 0x0FF0, 0x0FF0, 0x0FF0, 0x3FFC, 0x3FFC, 0x0FF0, 0x0FF0, 0x0FF0, 0x0FF0, 0x0FF0, 0x0FF0, 0x0C30, 0x0C30 };
static const uint16_t BUNNY16_WHITE1[16] = { 0x0000, 0x0000, 0x0000, 0x07E0, 0x05A0, 0x0660, 0x0E70, 0x07F0, 0x0620, 0x0420, 0x0620, 0x07E0, 0x0620, 0x0000, 0x0000, 0x0000 };
