"""Makes the bunny for every port from the Playdate version's image.

    python tools/make_sprites.py [wabbit_alpha.png]

The image, assets/wabbit_alpha.png by default (32x32, grey + alpha, copied from
Timofffee/bunnymark-playdate's Source/images, itself raylib's wabbit_alpha), has two
colours where it is opaque: black and white.

Every port draws the same bunny, the image at half size, 16x16, so the frame rates of
different machines measure the same work per bunny (only the screen each clears and sends
differs). Each 2x2 block is opaque when at least two of its pixels are, and black when at
least two are black; plain nearest neighbour loses the eyes and the outline.

- CHGame: a CHGfx span sprite (gfx_sprite4): w, h, then per row the number of runs and
  one byte per run, (len - 1) << 4 | colour, colour 15 = transparent, trailing
  transparency left out. Colours are palette indices: 0 black, 1 white.
- AKA and SDL: a list of runs per row (x, length, black or white) that the ports fill
  straight into a frame buffer (SDL also builds its texture from them).
- Arduboy (1 bit): Arduboy2's Sprites::drawPlusMask format: width, height, then for each
  8-row page and each column an image byte and a mask byte (bit 0 = top row). The port
  shows the display inverted, as the Playdate's white background, so an image bit of 1
  is black and 0 is white; the mask says which pixels are drawn at all.
- ESPboy and the ports sharing common/: runs per row and 1 bpp masks (below).
- Vircon32: a texture for its GPU (below).
"""
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "assets", "wabbit_alpha.png")

BLACK, WHITE, CLEAR = 0, 1, 15


def load():
    im = Image.open(SRC).convert("LA")
    w, h = im.size
    return [[CLEAR if im.getpixel((x, y))[1] < 128 else (BLACK if im.getpixel((x, y))[0] < 128 else WHITE)
             for x in range(w)] for y in range(h)]


def half(px):
    out = []
    for y in range(len(px) // 2):
        row = []
        for x in range(len(px[0]) // 2):
            block = [px[2 * y + dy][2 * x + dx] for dy in (0, 1) for dx in (0, 1)]
            opaque = sum(1 for c in block if c != CLEAR)
            black = sum(1 for c in block if c == BLACK)
            row.append(CLEAR if opaque < 2 else (BLACK if black >= 2 else WHITE))
        out.append(row)
    return out


def runs(row):
    """(x, length, colour) of every run of one colour, transparent ones included"""
    out, x = [], 0
    while x < len(row):
        n = 1
        while x + n < len(row) and row[x + n] == row[x]:
            n += 1
        out.append((x, n, row[x]))
        x += n
    return out


def sprite4(px):
    data = [len(px[0]), len(px)]
    for row in px:
        rr = runs(row)
        while rr and rr[-1][2] == CLEAR:          # trailing transparency is left out
            rr.pop()
        codes = []
        for _x, n, c in rr:
            while n > 0:                          # a run is at most 16 pixels
                k = min(n, 16)
                codes.append(((k - 1) << 4) | c)
                n -= k
        data.append(len(codes))
        data += codes
    return data


def hexlines(values, per=16):
    return ",\n".join("    " + ", ".join("0x%02X" % v for v in values[i:i + per])
                      for i in range(0, len(values), per))


def main():
    px = load()
    small = half(px)

    chg = sprite4(small)
    path = os.path.join(HERE, "chgame", "BunnyMark", "bunny.h")
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16,\n"
                "// a CHGfx span sprite (gfx_sprite4). Colour 0 black, 1 white, 15 transparent.\n"
                "#pragma once\n#include <stdint.h>\n\n"
                "static const uint8_t BUNNY[%d] = {\n%s\n};\n" % (len(chg), hexlines(chg)))
    print("wrote", path, len(chg), "bytes")

    spans, rows = [], []
    for row in small:
        rows.append(len(spans))
        spans += [(x, n, c) for x, n, c in runs(row) if c != CLEAR]
    rows.append(len(spans))
    # the AKA and the SDL ports (C++ and C)
    for path in (os.path.join(HERE, "aka", "main", "bunny.h"), os.path.join(HERE, "sdl", "bunny.h")):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", newline="\n") as f:
            f.write("// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16 as\n"
                    "// runs per row. BUNNY_ROWS[y]..BUNNY_ROWS[y + 1] index the runs of row y.\n"
                    "#pragma once\n#include <stdint.h>\n\n"
                    "#define BUNNY_W %d\n#define BUNNY_H %d\n\n"
                    "typedef struct BunnyRun { uint8_t x, len, white; } BunnyRun;\n\n" % (len(small[0]), len(small)))
            f.write("static const uint16_t BUNNY_ROWS[%d] = { %s };\n\n"
                    % (len(rows), ", ".join(str(r) for r in rows)))
            f.write("static const BunnyRun BUNNY_RUNS[%d] = {\n%s\n};\n" % (
                len(spans), ",\n".join("    { %d, %d, %d }" % s for s in spans)))
        print("wrote", path, len(spans), "runs")

    data = [len(small[0]), len(small)]
    for page in range(len(small) // 8):           # pages of 8 rows
        for x in range(len(small[0])):
            image = mask = 0
            for y in range(8):
                c = small[page * 8 + y][x]
                if c != CLEAR:
                    mask |= 1 << y
                if c == BLACK:
                    image |= 1 << y
            data += [image, mask]
    path = os.path.join(HERE, "arduboy", "BunnyMark", "bunny.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16,\n"
                "// for Sprites::drawPlusMask. Image bit 1 = black on the inverted display, mask\n"
                "// bit 1 = drawn.\n"
                "#pragma once\n#include <avr/pgmspace.h>\n\n"
                "//%s\n" % "\n//".join("    " + "".join(".#o"[(c == WHITE) + (c != CLEAR)] for c in r)
                                       for r in small))
        f.write("const uint8_t BUNNY[] PROGMEM = {\n%s\n};\n" % hexlines(data))
    print("wrote", path, len(data), "bytes")

    # ESPboy (128x128 like the CHGame): the same 16x16 bunny, ready for each depth the
    # port's frame sprite can have, so it is written straight into the sprite's memory
    # with nothing converted: the runs per row for 16 and 8 bpp (the port fills them
    # with that depth's white and black), and per row a 16-bit mask of the pixels that
    # are drawn and a 16-bit pattern of the white ones for 1 bpp, bit 15 the leftmost
    # pixel, as the sprites pack theirs most significant bit first. In RAM (no PROGMEM):
    # the ESP8266's flash takes 32-bit reads only
    spans, rows = [], []
    for row in small:
        rows.append(len(spans))
        spans += [(x, n, c) for x, n, c in runs(row) if c != CLEAR]
    rows.append(len(spans))
    masks, whites = [], []
    for row in small:
        m = w = 0
        for x, c in enumerate(row):
            if c != CLEAR:
                m |= 0x8000 >> x
            if c == WHITE:
                w |= 0x8000 >> x
        masks.append(m)
        whites.append(w)
    path = os.path.join(HERE, "espboy", "BunnyMark", "bunny.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16\n"
                "// (as on the CHGame), for each depth of the frame sprite:\n"
                "// - 16 and 8 bpp: runs per row, BUNNY_ROWS[y]..BUNNY_ROWS[y + 1] index those of row y\n"
                "// - 1 bpp: BUNNY_MASK1[y] the pixels drawn, BUNNY_WHITE1[y] the white ones,\n"
                "//   bit 15 the leftmost pixel\n"
                "#pragma once\n#include <stdint.h>\n\n"
                "#define BUNNY_W %d\n#define BUNNY_H %d\n\n"
                "typedef struct BunnyRun { uint8_t x, len, white; } BunnyRun;\n\n" % (len(small[0]), len(small)))
        f.write("static const uint8_t BUNNY_ROWS[%d] = { %s };\n\n"
                % (len(rows), ", ".join(str(r) for r in rows)))
        f.write("static const BunnyRun BUNNY_RUNS[%d] = {\n%s\n};\n\n" % (
            len(spans), ",\n".join("    { %d, %d, %d }" % s for s in spans)))
        f.write("static const uint16_t BUNNY_MASK1[%d] = { %s };\n" % (
            len(masks), ", ".join("0x%04X" % v for v in masks)))
        f.write("static const uint16_t BUNNY_WHITE1[%d] = { %s };\n" % (
            len(whites), ", ".join("0x%04X" % v for v in whites)))
    print("wrote", path, len(spans), "runs and 1 bpp masks")

    # The ports that keep their whole screen in RAM (pybadge/, picosystem/, pimoroni2350/, thumbycolor/),
    # in the
    # same forms, as BUNNY16_; the 1 bpp masks are a uint16_t a row, the top bit the leftmost
    # pixel. Written to common/ and copied into each of those sketches with the rest of common/
    # (an Arduino sketch only compiles what is in its own folder)
    path = os.path.join(HERE, "common", "bunny.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16\n"
                "// (BUNNY16_), for each depth of the screen buffer:\n"
                "// - 16 and 8 bpp: runs per row, _ROWS[y].._ROWS[y + 1] index those of row y\n"
                "// - 1 bpp: _MASK1[y] the pixels drawn, _WHITE1[y] the white ones, the top bit\n"
                "//   the leftmost pixel\n"
                "#pragma once\n#include <stdint.h>\n\n"
                "typedef struct BunnyRun { uint8_t x, len, white; } BunnyRun;\n")
        for grid in (small,):
            size = len(grid[0])
            pre = "BUNNY%d_" % size
            spans, rows, masks, whites = [], [], [], []
            for row in grid:
                rows.append(len(spans))
                spans += [(x, n, c) for x, n, c in runs(row) if c != CLEAR]
                m = w = 0
                for x, c in enumerate(row):
                    if c != CLEAR:
                        m |= 1 << (size - 1 - x)
                    if c == WHITE:
                        w |= 1 << (size - 1 - x)
                masks.append(m)
                whites.append(w)
            rows.append(len(spans))
            mtype, digits = ("uint16_t", 4) if size == 16 else ("uint32_t", 8)
            f.write("\n#define %sW %d\n#define %sH %d\n" % (pre, size, pre, len(grid)))
            f.write("static const uint16_t %sROWS[%d] = { %s };\n" % (
                pre, len(rows), ", ".join(str(r) for r in rows)))
            f.write("static const BunnyRun %sRUNS[%d] = {\n%s\n};\n" % (
                pre, len(spans), ",\n".join("    { %d, %d, %d }" % s for s in spans)))
            f.write("static const %s %sMASK1[%d] = { %s };\n" % (
                mtype, pre, len(masks), ", ".join("0x%0*X" % (digits, v) for v in masks)))
            f.write("static const %s %sWHITE1[%d] = { %s };\n" % (
                mtype, pre, len(whites), ", ".join("0x%0*X" % (digits, v) for v in whites)))
    print("wrote", path)
    shared = [os.path.join(HERE, "common", name) for name in ("bunny.h", "BunnyFrame.h", "BunnyGame.h")]
    shared.append(os.path.join(HERE, "sdl", "font8x8_basic.h"))
    for sketch in ("pybadge", "picosystem", "pimoroni2350", "thumbycolor"):
        folder = os.path.join(HERE, sketch, "BunnyMark")
        os.makedirs(folder, exist_ok=True)
        for source in shared:
            with open(source, "rb") as f:
                data = f.read()
            with open(os.path.join(folder, os.path.basename(source)), "wb") as f:
                f.write(data)
    print("copied common/ and the font into pybadge/, picosystem/, pimoroni2350/ and thumbycolor/")

    # Vircon32 (640x360): one texture for its GPU, the bunny (black, white and transparent) at
    # 0,0 and a 4x4 black block at 32,0, which the port stretches into the box's lines (the
    # console draws texture regions only, it has no line drawing)
    tex = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
    for y, row in enumerate(small):
        for x, c in enumerate(row):
            if c != CLEAR:
                tex.putpixel((x, y), (0, 0, 0, 255) if c == BLACK else (255, 255, 255, 255))
    for y in range(4):
        for x in range(32, 36):
            tex.putpixel((x, y), (0, 0, 0, 255))
    path = os.path.join(HERE, "vircon32", "assets", "bunny.png")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tex.save(path)
    print("wrote", path)

    # TIC-80: tiles 0, 1, 16 and 17 (spr(0, x, y, key, 1, 0, 0, 2, 2) draws them as one 16x16
    # sprite), one hex digit per pixel as a .lua cart writes them, black colour 0, white 12, the
    # transparent pixels colour 2 (the cart's colour key). The palette is TIC-80's default
    # (Sweetie 16) with 0 made pure black and 12 pure white
    tic = {0: "0", 1: "c", CLEAR: "2"}
    tiles = []
    for ty in range(2):
        for tx in range(2):
            index = ty * 16 + tx
            rows = "".join("".join(tic[small[ty * 8 + y][tx * 8 + x]] for x in range(8)) for y in range(8))
            tiles.append("-- %03d:%s" % (index, rows))
    palette = list(bytes.fromhex("1a1c2c5d275db13e53ef7d57ffcd75a7f07038b764257179"
                                 "29366f3b5dc941a6f673eff7f4f4f494b0c2566c86333c57"))
    palette[0:3] = [0, 0, 0]
    palette[36:39] = [255, 255, 255]
    path = os.path.join(HERE, "tic80", "bunnymark.lua")
    replace_section(path, "-- <TILES>\n", "-- </TILES>\n", "\n".join(tiles) + "\n")
    replace_section(path, "-- <PALETTE>\n", "-- </PALETTE>\n", "-- 000:" + bytes(palette).hex() + "\n")
    print("wrote the bunny and the palette into", path)

    # PICO-8: sprites 0, 1, 16 and 17, the top left 16x16 of the sheet (spr(0, x, y, 2, 2)), one
    # hex digit per pixel. White is colour 7; black and transparent are both colour 0, PICO-8's
    # transparent one (and v32lua's, which ignores palt()): the cart draws on black, so the bunny's
    # black parts show the background
    p8 = {0: "0", 1: "7", CLEAR: "0"}
    rows = ["".join(p8[c] for c in row) + "0" * (128 - len(row)) for row in small]
    path = os.path.join(HERE, "pico8", "bunnymark.p8")
    with open(path, encoding="utf-8", newline="") as f:
        text = f.read()
    text = text[:text.index("__gfx__\n") + len("__gfx__\n")] + "\n".join(rows) + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote the bunny into", path)


def replace_section(path, start, end, content):
    """Replaces what lies between the lines start and end of a text file with content"""
    with open(path, encoding="utf-8", newline="") as f:
        text = f.read()
    a = text.index(start) + len(start)
    b = text.index(end, a)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text[:a] + content + text[b:])


if __name__ == "__main__":
    main()
