// Generated by tools/make_sprites.py from wabbit_alpha.png: the bunny at 16x16 as
// runs per row. BUNNY_ROWS[y]..BUNNY_ROWS[y + 1] index the runs of row y.
#pragma once
#include <stdint.h>

#define BUNNY_W 16
#define BUNNY_H 16

typedef struct BunnyRun { uint8_t x, len, white; } BunnyRun;

static const uint16_t BUNNY_ROWS[17] = { 0, 2, 3, 4, 7, 14, 19, 24, 27, 32, 37, 42, 45, 50, 51, 53, 55 };

static const BunnyRun BUNNY_RUNS[55] = {
    { 4, 3, 0 },
    { 9, 3, 0 },
    { 4, 8, 0 },
    { 4, 8, 0 },
    { 4, 1, 0 },
    { 5, 6, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 1, 1 },
    { 6, 1, 0 },
    { 7, 2, 1 },
    { 9, 1, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 2, 0 },
    { 9, 2, 1 },
    { 11, 1, 0 },
    { 2, 2, 0 },
    { 4, 3, 1 },
    { 7, 2, 0 },
    { 9, 3, 1 },
    { 12, 2, 0 },
    { 2, 3, 0 },
    { 5, 7, 1 },
    { 12, 2, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 1, 1 },
    { 6, 4, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 6, 1 },
    { 11, 1, 0 },
    { 4, 1, 0 },
    { 5, 2, 1 },
    { 7, 3, 0 },
    { 10, 1, 1 },
    { 11, 1, 0 },
    { 4, 8, 0 },
    { 4, 2, 0 },
    { 10, 2, 0 },
    { 4, 2, 0 },
    { 10, 2, 0 }
};
